# Set a plain language title for the site.
title: USWDS Design Token Guide Presentation

# Write a short description for the site. This is used for "meta description."
description: A presentation of what led to creating a guide to using design tokens, how the guide is organized, and how to give feedback on the guide.

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Enable for live hosting on GitHub Pages
baseurl: /design-token-presentation

# Remove generation of additional style.css
theme: null

collections:
  slides:
    output: true
